### PR TITLE
Compatibility with Pydantic 2, and Streamlit 1.31, modern building of package

### LINKED ISSUE #8: Use built-in streamlit link button for the hosted UI login button
Streamlit has introduced a [new button element](https://docs.streamlit.io/library/api-reference/widgets/st.link_button) that opens an arbitrary link in a new browser tab. This is exactly the functionality simulated in [CognitoHostedUIAuthenticator.show_login_button](https://github.com/pop-srw/streamlit-cognito-auth/blob/391f8708c3411e258c9c7a5b38d9a6d5427e6247/src/streamlit_cognito_auth/auth.py#L616) so the standardized way of button creation should be preferred.

### LINKED ISSUE #9: Should not be printing credentials
https://github.com/pop-srw/streamlit-cognito-auth/blob/391f8708c3411e258c9c7a5b38d9a6d5427e6247/src/streamlit_cognito_auth/auth.py#L298

### PR DESCRIPTION
**Pull request by lambda-science**
Changelog:
- Compatibility with Pydantic 2 (just an update of the dependencies)
- Compatibility with Streamlit 1.31 (`query_params` was experimental and changed behaviour now)
- Changed the "Show Login Button" to native Streamlit.
- More modern way of building the library -> from setup.py to pyproject.toml (you can still use the classic build command)
- Removed old print statements

Issues:
- Can't use cookies with Hosted Login Page, don't know why
- In some setup, using the `use_cookies=True` create big empty space (non-hosted version) corresponding to the hidden login form.

Fix #8
Fix #9

### CODE REVIEW

**Comment by lambda-science** [comment]
@mrtj thoughts ?
Also wish to fix use_cookies with hosted app because it's annoying to re-log on refresh...

**Comment by shreyarm-aws** [comment]
Hi team, please approve this PR, the pydantic dependency conflict is causing a multitude of issues with development.

**Comment by lambda-science** [comment]
Latest commit fix the vertical space when cookie=True see https://github.com/Mohamed-512/Extra-Streamlit-Components/issues/62

**Comment by lambda-science** [comment]
Nevermind, this is really spagetthi code I can't fix the cookies not properly not loading. I'm tired of this lib.

**Comment by lambda-science** [comment]
> Nevermind, this is really spagetthi code I can't fix the cookies not properly not loading on page refresh. I'm tired of this lib.

Last commit fix this issue, but it's not proper I don't understand why / how.

**Comment by lambda-science** [comment]
FINALLY FOUND THIS F- BUG, god it was annoying.

You should add a very small `time.sleep()` after a `.get_all()` on cookie manager for it to have time to load them.
See: https://discuss.streamlit.io/t/finally-i-find-a-right-way-to-use-extra-cookie-manager/47094

Maybe it might need some more optimization to reduce the number of time it get called...

Cookie are now working and no more vertical space.

**Comment by lambda-science** [comment]
Update: the issue is now a spam of 
```
claims, user = verify_access_token(
raise TokenVerificationException(e)
streamlit_cognito_auth.exceptions.TokenVerificationException: Your 'access_token' token could not be verified (Signature has expired).
```
and stuff like
```
WARNING:streamlit_cognito_auth.auth:Requested to delete non existing cookie: access_token
```
and stuff like
```
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/site-packages/streamlit/util.py:227: RuntimeWarning: coroutine 'expire_cache' was never awaited
```

This version 1.3.0 and 1.4.0 (this MR) are truly mess I strongly suggest everyoen to revert to 1.2.0 or just stay away. Horrible experience so far.

**Comment by pop-srw** [comment]
@lambda-science. I apologize for the delay. Your PR is now merged, it's really great work. It solves several key problems and many thanks for the valuable contribution. Would you be interested in becoming a project maintainer? If so, please let me know.

**Pull request merged**
