### PR TITLE
Authorize with cognito hosted UI

### PR DESCRIPTION
**Pull request by mrtj**
This PR introduces the feature of authorizing the streamlit app with [AWS Cognito hosted UI](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-integration.html). The PR also includes a specific example in the examples folder.

### CODE REVIEW

**Review by nasirtrekker — APPROVED** [review]

**Comment by shreyasdamle** [comment]
Hi team, can you merge this PR and release the changes? I would love to try out this feature.

**Comment by lambda-science** [comment]
Same :)

**Comment by pop-srw** [comment]
I apologize for the delayed response. I want to express my gratitude to everyone who has shown interest in my project. I'd like to give special thanks to @mrtj for your contribution, your work is truly amazing. Thank you so much.

**Comment by lambda-science** [comment]
Would be nice to maybe update to pydantic >2 @mrtj 👀Unfortunatly I have dep conflict with Pydantic <1 ahah

**Comment by mrtj** [comment]
@lambda-science great idea! Could you open a separate issue to track this request?

**Comment by lambda-science** [comment]
> @lambda-science great idea! Could you open a separate issue to track this request?

I forked and will try to see if it works out of the box with pydantic 2
If yes, I will do a PR

**Comment by lambda-science** [comment]
> @lambda-science great idea! Could you open a separate issue to track this request?

Btw after this update, in my streamlit mult-page app I have a lot of empty space after logging in.
Have you already experienced that ? How to solve it @mrtj 
image

**Comment by lambda-science** [comment]
> > @lambda-science great idea! Could you open a separate issue to track this request?
> 
> Btw after this update, in my streamlit mult-page app I have a lot of empty space after logging in. Have you already experienced that ? How to solve it @mrtj image

Heh this is **solved** by using `use_cookies=False` not sure what's the impact of not using cookie !

**Comment by lambda-science** [comment]
Sorry for the spam maybe I really should open a private chat or another issue but with latest streamlit, the new hosted UI show this warning:
image
And I can't use hosted UI. When I log in, the page refresh and I'm not logged in (wether with ou without use of cookies). 
Maybe I didn't configure my Cognito properly. @mrtj

**Comment by lambda-science** [comment]
Please @mrtj do you know why when `use_cookies=True` there is so much empty space face invisible login form ? It's really annoying to use `use_cookies=False` my user need to login at each refresh :((
I spent so much time understanding where this bug comes from but I can't :/ @pop-srw

**Comment by lambda-science** [comment]
Related issue: https://github.com/Mohamed-512/Extra-Streamlit-Components/issues/62

**Pull request merged**
